name: CI

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.12"]
    env:
      OS: ${{ matrix.os }}
    #     container:
    #       image: pytorch/pytorch:2.4.0-cuda11.8-cudnn9-devel

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install CUDA Toolkit
      uses: Jimver/cuda-toolkit@v0.2.16
      with:
        cuda: "12.4.0"

    - name: List installed packages
      run: dpkg --get-selections | grep cuda

    - name: Verify CUDA installation
      run: |
        nvcc --version
        python -c "import torch; print(torch.cuda.is_available())"
