name: CI

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.12"]
    env:
      OS: ${{ matrix.os }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install CUDA Toolkit
      uses: Jimver/cuda-toolkit@v0.2.16
      with:
        cuda: "12.4.0"

    - name: Install dependencies
      run: |
          pip install .[dev] --index-url https://download.pytorch.org/whl/cu124

    - name: Verify CUDA installation
      run: |
        nvcc --version
        python -c "import torch; print(torch.cuda.is_available())"
