name: conda-deployment

on: [push]

jobs:
  main-package:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.12"]
    env:
      OS: ${{ matrix.os }}
      HUGGINGFACE_TOKEN: ${{ secrets.HUGGINGFACE_TOKEN }}

    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2
        with:
          mamba-version: "*"
          #use-mamba: true
          auto-update-conda: false
          environment-file: environment.yml
          auto-activate-base: false
          activate-environment: test
          python-version: ${{ matrix.python-version }}
          channels: conda-forge,defaults
          channel-priority: true
          show-channel-urls: true

      - name: Install dev-dependencies
        shell: bash -el {0}
        run: |
            # pip install .[test] --no-deps
            pip install pytest pytest-cov nbval

      - name: Run tests
        shell: bash -el {0}
        run: |
          conda info
          conda list
          conda config --show-sources
          conda config --show
          pytest -sv

      - name: test Jupyter notebook
        shell: bash -el {0}
        run: |
          conda activate test
          pip install -e . --no-deps
          pytest --nbval -k ".ipynb"
