name: CI

on: [push]

jobs:
  main-package:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.12"]
    env:
      OS: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

#       - name: Install CUDA Toolkit
#         uses: Jimver/cuda-toolkit@v0.2.16
#         with:
#           cuda: "12.4.0"
#           linux-local-args: '["--toolkit"]'

      - name: Install dependencies
        run: |
            pip install .[test]

#       - name: Verify CUDA installation
#         run: |
#             nvcc --version
#             python -c "import torch; print(torch.cuda.is_available())"

      - name: Run tests and generate coverage report
        run: |
            pytest -v --cov=serapeum --cov-report=xml
